gnumbers: ../metadata/GENOMES_2025-11-05_14-27-46_TNZ_Status1_7.txt
metadata: ../metadata/10k/metadata_reduced.tsv
path_to_db: /scicore/home/gagneux/GROUP/tbresearch/genomes/IN_PROGRESS/common_mappings/PipelineTB/v2
vcf: ../data/major_variants.merged.vcf.gz

outdir: 
  main: tanzania  # No slash at the end
  benchmarking: results
  
detettore:
  reference: ../data/MTBC0/MTBC0_v1.1.fasta
  is_target: 'software/detettore6110/resources/is_targets/IS6110.fasta'
  is_cluster: IS3_168
  seed_len: 20
  maxmissing: 4

alignment:
  maxmissing: 0.5

phylogeny:
  outgroup: G742339
  bootstraps: 1000

annotations:
  mtbc0: ../data/MTBC0/MTBC0v1.1_PGAP_annot.gff
  mtbc0_regions: ../data/MTBC0/MTBC0.genic_n_intergenic_regions.burden.tsv
  h37rv: ../data/H37Rv/GCF_000195955.2_ASM19595v2_genomic.gff
  mtbc0_h37rv_map: ../data/MTBC0/mtbc0_to_h37rv.genemap.tsv
  mtbc0_regions: ../data/MTBC0/MTBC0.genic_n_intergenic_regions.burden.tsv

gwas:
  permutations: 100

benchmarking:
  assemblies: config/datasets/30assemblies.tsv
  min_id: 0.9
  anchor_length: 300
  readlengths: [100, 150]
  coverages: [20, 30, 40, 50]
  hit_lengths: [20]
  min_cluster_size: [3]

niche_model_abc:
  ntips : 500
  nsimulations : 100000
